USE adlister_db;

INSERT INTO categories(name) VALUES
('For Sale'),
('Free'),
('Electronics'),
('Clothes and Accessories'),
('Vehicles'),
('Furniture'),
('Other'),
('Jobs'),
('Weekend Jobs'),
('Finance'),
('Manufacturing'),
('Sales'),
('Retail'),
('Community'),
('Volunteering'),
('Events'),
('Pets'),
('Local News'),
('Lost and Found'),
('Farmers'' Market'),
('Housing'),
('Real Estate'),
('House Swap'),
('House Parties'),
('Vacation Rentals'),
('Rooms Wanted'),
('For Rent'),
('Services'),
('Automotive'),
('Landscaping'),
('Farm and Garden'),
('Financial'),
('Gigs'),
('Crew'),
('Talent'),
('Musician'),
('Domestic');

