USE adlister_db;

INSERT INTO categories(name)
VALUES ('For Sale'),
       ('Free'),
       ('Electronics'),
       ('Clothes and Accessories'),
       ('Vehicles'),
       ('Furniture'),
       ('Other'),
       ('Jobs'),
       ('Weekend Jobs'),
       ('Finance'),
       ('Manufacturing'),
       ('Sales'),
       ('Retail'),
       ('Community'),
       ('Volunteering'),
       ('Events'),
       ('Pets'),
       ('Local News'),
       ('Lost and Found'),
       ('Farmers'' Market'),
       ('Housing'),
       ('Real Estate'),
       ('House Swap'),
       ('House Parties'),
       ('Vacation Rentals'),
       ('Rooms Wanted'),
       ('For Rent'),
       ('Services'),
       ('Automotive'),
       ('Landscaping'),
       ('Farm and Garden'),
       ('Financial'),
       ('Gigs'),
       ('Crew'),
       ('Talent'),
       ('Musician'),
       ('Domestic');

INSERT INTO users(username, email, password)
VALUES ('bobSchwab', 'bs@email.com','bob'),
       ('peterPan', 'pp@email.com','pete'),
       ('drdoom', 'doom@email.com','doom'),
       ('sonic', 'sanic@email.com','sonice'),
       ('knuckles', 'k@email.com','dawae'),
       ('alpacaFarm', 'as@email.com','paca'),
       ('TomCruise', 'scientologys@email.com','MI3'),
       ('Rick', 'ricks@email.com','rick'),
       ('Morty', 'morty@email.com','morty');

INSERT INTO ads(user_id, title, description)
VALUES (1,'Blade','The first blade'),
       (2,'Blade II','The second blade'),
       (3,'Blade III','The third blade'),
       (4,'Ice cubes (4)','frozen water'),
       (5,'Rusty Spoon','spoon'),
       (6,'Ramen','noodles'),
       (7,'Knuckle Sandwich','fight club'),
       (8,'Toothbrush (slightly used','exactly what it sounds like'),
       (9,'Meat and Potatoes','potatoes and meat');

